### ISSUE TITLE
Transfer gem ownership

### ISSUE THREAD

**Issue by strogonoff** [riboseinc/jekyll-theme-open-hub#1]
@ronaldtse, can you let me know which Rubygems.org user should be made owner of the Open Hub theme gem?

**Comment by ronaldtse** [comment]
Can you help add “ribose” as a gem owner for now?

For gemspec contact you can view our other gems — the author should just be company name, contact should be “open.source@ribose.com”. Thanks!

**Comment by strogonoff** [comment]
Added new owner, kept my ownership to be able to push while theme is being developed:

```console
mac:~$ gem owner jekyll-theme-open-hub -a "ronald.tse@ribose.com"
Owner added successfully.
Owners for gem: jekyll-theme-open-hub
- ronald.tse@ribose.com
- anton@strogonoff.name
```
